### ISSUE TITLE
Any polyfill could be used currently?

### ISSUE THREAD

**Issue by NE-SmallTown** [WICG/largest-contentful-paint#1]
FIrst, thanks for this proposal! I have read README and the slide which compare 6 ways. So I'm thinking, what could we do(by js) to measure/get the similar LargestContentfulPaint  at now, but seems too expensive for doing this maybe?

**Comment by npm1** [comment]
Just saw this, sorry! Yea I agree that a polyfill for this would be pretty expensive. A related API that could help if you have some set of 'plausible candidates' is the Element Timing API: https://github.com/WICG/element-timing

**Comment by yoavweiss** [comment]
@NE-SmallTown I hope that answers your question! Closing, but feel free to comment if it hasn't
