### ISSUE TITLE
Can LargestContentfulPaint's element attribute be null?

### ISSUE THREAD

**Issue by foolip** [WICG/largest-contentful-paint#16]
https://wicg.github.io/largest-contentful-paint/#sec-largest-contentful-paint-interface says:
```webidl
interface LargestContentfulPaint : PerformanceEntry {
    readonly attribute DOMHighResTimeStamp renderTime;
    readonly attribute DOMHighResTimeStamp loadTime;
    readonly attribute unsigned long size;
    readonly attribute DOMString id;
    readonly attribute DOMString url;
    readonly attribute Element? element;
};
```

However, https://wicg.github.io/largest-contentful-paint/#sec-processing-model is the only place that creates instances of `LargestContentfulPaint`, and there *element* cannot be null.

If it can't be null the `?` can be removed from the Web IDL and readers need not wonder :)

**Comment by npm1** [comment]
If the Element is disconnected then 'element' attribute getter should return null. Note that the 'element' attribute getter is NOT defined to just be the 'value it was initialized to'.

**Comment by foolip** [comment]
Thanks, that explains why it could return null. Still, why is it like this? One still has to hold old to the element internally and the getter can start returning it again later. Is exposing "is it connected to the same document as before" the direct purpose, or is some optimization made possible this way?

**Comment by npm1** [comment]
The reason is to not hold on to the element forever. The LargestContentfulPaint entry could live after the Element is removed from the DOM tree, so the idea is that we keep exposing some properties of it but the user agent will be allowed to garbage-collect the Element (we should not block garbage collection of Elements on these entries).

**Comment by foolip** [comment]
I see, not keeping the Element alive was the motivation. I've filed https://github.com/WICG/largest-contentful-paint/issues/29 and a similar issue on Element Timing since it looks like the spec doesn't quite achieve this, but it's complex so I'm not entirely sure.

**Comment by foolip** [comment]
Closing this since it has been answered and there's a more specific issue filed.
