### ISSUE TITLE
"potentially add a LargestContentfulPaint entry" is never invoked

### ISSUE THREAD

**Issue by foolip** [WICG/largest-contentful-paint#17]
https://wicg.github.io/largest-contentful-paint/#potentially-add-a-largestcontentfulpaint-entry is the entry point to the interesting bits, but it appears that it's never in invoked.

It appears that much of the difficulty of implementing this would be in when to invoke that algorithm, or should the observable behavior be as if it's invoked for every paint?

**Comment by foolip** [comment]
I went looking for examples, and https://w3c.github.io/resource-timing/#sec-process says "For each resource whose Request has a non-null client, perform the following steps". Something like that but for rendering is probably what's needed.

**Comment by foolip** [comment]
There's a minor issue I'll just tag on here: probably the *document* variable isn't needed, just get it from *element*'s node document. And something should presumably exit early if *element* isn't connected.

**Comment by yoavweiss** [comment]
@foolip - it's invoked from [Element Timing](https://wicg.github.io/element-timing/#sec-report-image-element). I should probably add a note to that effect.

**Comment by npm1** [comment]
Note that I'm on the process of changing some of this - see https://github.com/WICG/element-timing/pull/16. We could have a non-normative note to explain where it is called from, but technically the correct way to spec this is by doing the direct calling, which is what we're doing?

**Comment by foolip** [comment]
Ah great, looks like it's invoked from two places:
https://wicg.github.io/element-timing/#report-image-element-timing
https://wicg.github.io/element-timing/#report-text-element-timing

That's fine and how things should look in spec land, I just didn't know where to look. You could add a note if you like, but not necessary. It'd be good to clarify "This API relies on Element Timing for its underlying primitives" though, since LCP isn't built on top of ET in the way this would suggest.

**Comment by foolip** [comment]
It looks like there's also a argument mismatch. The algorithm in LCP takes 6 arguments, but ET invokes it with 5.

**Comment by npm1** [comment]
Yep, that's due to my recent PR that added loadTime, the ElementTiming counterpart hasn't landed yet. Sorry about that!

**Comment by yoavweiss** [comment]
I think we'd be able to close this once https://github.com/WICG/element-timing/pull/16 lands. Is that correct?

**Comment by foolip** [comment]
Yep, this issue was invalid to begin with, but that issue is sorta related. I'll close this though.
