### ISSUE TITLE
What is the id attribute for?

### ISSUE THREAD

**Issue by foolip** [WICG/largest-contentful-paint#19]
It looks like `entry.id` will be the same as `entry.element.id`. If so, why eagerly extract this information?

If the id content attribute changes then `entry.id` will still be the old value, but I suspect this isn't the reason for extracting the information.

**Comment by npm1** [comment]
Hmm well we initially didn't have the 'element'. But if an element is disconnected somehow then you can still obtain the id from this attribute but would not be able to from entry.element. Does that make sense?

**Comment by foolip** [comment]
I see, so this is somewhat entangled with https://github.com/WICG/largest-contentful-paint/issues/16.

I also just filed https://github.com/WICG/element-timing/issues/20, will file a twin issue for this spec if it has the same issue.

**Comment by foolip** [comment]
Looks like LCP doesn't have the same problem.

**Comment by foolip** [comment]
https://github.com/WICG/largest-contentful-paint/issues/29 is somewhat related, in that it sounds like the reason for the `id` attribute is that the element might go away.

**Comment by npm1** [comment]
Yep! So... can we close this issue?

**Comment by foolip** [comment]
Yes, my initial notion that one could just use `entry.element` is no good, more likely `entry.element` needs to be removed or made to return null more eagerly, so a static copy of the id attribute is the only thing by which one could identify elements absent `entry.element`.
