### ISSUE TITLE
Where does the request come from?

### ISSUE THREAD

**Issue by foolip** [WICG/largest-contentful-paint#20]
https://wicg.github.io/largest-contentful-paint/#potentially-add-a-largestcontentfulpaint-entry needs a Request object as its input. Where does this come from? It seems like for some elements like `<p>large text</p>` there wouldn't be a request at all. https://github.com/web-platform-tests/wpt/blob/master/largest-contentful-paint/observe-text.html requires `entry.url` to be the empty string in this case, but this and the other assertions around `entry.url` should be explainable by following the spec.

Would be resolved by https://github.com/WICG/largest-contentful-paint/issues/17, this is just a specific question about that.

**Comment by yoavweiss** [comment]
Does https://github.com/WICG/largest-contentful-paint/issues/17#issuecomment-514238711 answer your question?

**Comment by foolip** [comment]
Yes it does, and it's clear from that that *request* can be null. This needs to be handled in FCP.

**Comment by yoavweiss** [comment]
> This needs to be handled in FCP.

Good catch! Thanks! :)
