### ISSUE TITLE
LargestContentfulPaint keeps its Element alive

### ISSUE THREAD

**Issue by foolip** [WICG/largest-contentful-paint#29]
This is a mirror issue of https://github.com/WICG/element-timing/issues/21. There is a similar mismatch between [Chromium](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/timing/largest_contentful_paint.h?l=48&rcl=661924ec5de0167e50003b85c83e0bd2a735b6d9) and the [spec](https://wicg.github.io/largest-contentful-paint/#sec-largest-contentful-paint-interface) here it seems.

(Filing eagerly, pardon if the original issue turns out to be void.)

**Comment by yoavweiss** [comment]
Fixed by https://github.com/WICG/element-timing/pull/24
