### ISSUE TITLE
Investigate element removal

### ISSUE THREAD

**Issue by npm1** [WICG/largest-contentful-paint#41]
The spec does not handle element removal at all. When content is removed, previous content could become the largest, and a new entry would need to be exposed for such content.

**Comment by anniesullie** [comment]
Update: we're investigating whether element removal should be in the spec; we found several cases where it has a very negative effect on carousels: https://github.com/anniesullie/LCP_Examples/blob/master/removed_from_dom/README.md

Currently working on gathering a larger data set.

**Comment by npm1** [comment]
Ok changed the title as the spec and explainers now roughly cover removal. If we choose to not handle removal then they need to be updated.

**Comment by npm1** [comment]
We've decided to allow removed content to remain as valid LCP candidates, so now we need to update the explainer and spec accordingly.
