### ISSUE TITLE
Can LCP exceed PLT

### ISSUE THREAD

**Issue by ThierryMajutec** [WICG/largest-contentful-paint#60]
Hi, 
Can the LCP value exceeds PLT value ?
Do you see any scenario where it would be possible ?

Thanks

**Comment by anniesullie** [comment]
How do you define "PLT"? Do you mean when the window.onload event fires? If so, yes, LCP can be later than that if the largest contenful image or text on the page paints after the onload event.

An analysis of HttpArchive data showed this is unusual but it does happen: https://datastudio.google.com/c/u/0/reporting/1sCHMXg3hgza3vqNVhDFAftYRgI94s2da/page/rOI5

**Comment by ThierryMajutec** [comment]
PLT : Page Load Time, as defined in W3C Time Navigation.


On 24-09-20 16:21:16, anniesullie <notifications@github.com> wrote:

How do you define "PLT"? Do you mean when the window.onload event fires? If so, yes, LCP can be later than that if the largest contenful image or text on the page paints after the onload event.

An analysis of HttpArchive data showed this is unusual but it does happen: https://datastudio.google.com/c/u/0/reporting/1sCHMXg3hgza3vqNVhDFAftYRgI94s2da/page/rOI5

**Comment by npm1** [comment]
Is it ok to close this?

**Comment by ThierryMajutec** [comment]
> Is it ok to close this?

Yes, thanks !
