### ISSUE TITLE
Are the units of LargestContentfulPaint.size in pixels?

### ISSUE THREAD

**Issue by dashed** [WICG/largest-contentful-paint#76]
Are the units of `LargestContentfulPaint.size` in pixels?

It's non-obvious to me from the spec that it is: https://wicg.github.io/largest-contentful-paint/#dom-largestcontentfulpaint-size

**Comment by npm1** [comment]
Good question, I believe the answer should be layout units. Perhaps we can add a clarification in the readme or the spec?

**Comment by npm1** [comment]
Oh yea the algorithm computing the rect is actually coming from Element Timing, so it does seem hard to reason about it. I can add some text to the explainer (the README) to make it clearer.
